-- Seed: articles (aktuality)
insert into articles (title, excerpt, published_at, is_published) values
  ('Jarní zahradní slavnost', 'Zveme všechny klienty i jejich rodiny na tradiční jarní slavnost v naší zahradě. Připraveny jsou soutěže, občerstvení a hudební vystoupení.', '2026-02-28T10:00:00Z', true),
  ('Nová rehabilitační místnost', 'S radostí oznamujeme otevření nově zrekonstruované rehabilitační místnosti s moderním vybavením pro fyzioterapii.', '2026-02-15T10:00:00Z', true),
  ('Výtvarná výstava klientů', 'V prostorách společenské místnosti probíhá výstava výtvarných prací našich klientů. Výstava potrvá do konce března.', '2026-02-03T10:00:00Z', true);

-- Seed: page_sections
insert into page_sections (id, title, subtitle, content) values
  ('about', 'O nás', null, '{"text": "Domov důchodců Řepy funguje již více než 25 let v klidné rezidenční čtvrti Prahy 17. Nabízíme důstojné bydlení a komplexní péči pro seniory, kteří potřebují pomoc v každodenním životě.", "text2": "Náš areál je obklopen zelení a nabízí příjemné prostředí pro odpočinek i aktivní trávení času.", "values": [{"title": "Péče s láskou", "description": "Individuální přístup ke každému klientovi. Nasloucháme a přizpůsobujeme péči jeho potřebám."}, {"title": "Komunita", "description": "Bohatý společenský program, kulturní akce a možnost trávit čas s vrstevníky i rodinou."}, {"title": "Bezpečí", "description": "Moderní vybavení, 24hodinová zdravotní služba a bezbariérový přístup v celém areálu."}]}'),
  ('services', 'Naše služby', 'Poskytujeme komplexní péči, která pokrývá všechny potřeby našich klientů.', '[{"icon": "🏠", "title": "Ubytování", "description": "Jednolůžkové i dvoulůžkové pokoje s vlastním sociálním zařízením, nábytek na míru, televizí a Wi-Fi."}, {"icon": "🍽️", "title": "Stravování", "description": "Celodenní stravování 5× denně, dietní i diabetická strava. Čerstvé suroviny od lokálních dodavatelů."}, {"icon": "🏥", "title": "Zdravotní péče", "description": "Nepřetržitá zdravotní služba, pravidelné lékařské vizity, podávání léků a spolupráce se specialisty."}, {"icon": "💪", "title": "Rehabilitace", "description": "Fyzioterapie, ergoterapie a cvičení pod vedením odborníků. Moderně vybavená rehabilitační místnost."}, {"icon": "🎨", "title": "Volnočasové aktivity", "description": "Výtvarné dílny, hudební terapie, zahradničení, výlety a společenské hry. Každý den něco nového."}, {"icon": "📋", "title": "Sociální poradenství", "description": "Pomoc s vyřízením příspěvku na péči, komunikace s úřady a podpora při řešení životních situací."}]'),
  ('pricing', 'Ceník', 'Přehled orientačních cen za ubytování a služby.', '{"rows": [{"service": "Jednolůžkový pokoj", "price": "18 500 Kč / měsíc"}, {"service": "Dvoulůžkový pokoj", "price": "14 200 Kč / měsíc"}, {"service": "Celodenní stravování (5× denně)", "price": "5 800 Kč / měsíc"}, {"service": "Základní ošetřovatelská péče", "price": "zahrnuto v ceně"}, {"service": "Rehabilitace (individuální)", "price": "350 Kč / sezení"}, {"service": "Rehabilitace (skupinová)", "price": "150 Kč / sezení"}, {"service": "Praní a žehlení prádla", "price": "zahrnuto v ceně"}, {"service": "Kadeřnické služby", "price": "dle ceníku poskytovatele"}], "note": "Klienti s přiznaným příspěvkem na péči (stupně I–IV) mohou část nákladů hradit z tohoto příspěvku. Rádi vám pomůžeme s vyřízením žádosti."}'),
  ('faq', 'Časté dotazy', 'Odpovědi na nejčastější otázky.', '[{"question": "Jak podat žádost o umístění?", "answer": "Žádost můžete podat osobně, poštou nebo e-mailem. K žádosti přiložte kopii občanského průkazu, lékařské zprávy a rozhodnutí o příspěvku na péči (pokud máte). Formulář žádosti je ke stažení na našich stránkách nebo k vyzvednutí na recepci."}, {"question": "Jaké jsou podmínky přijetí?", "answer": "Přijímáme seniory od 65 let, kteří potřebují pravidelnou pomoc v každodenním životě. Podmínkou je podaná žádost, lékařské vyjádření a osobní pohovor. Přednost mají žadatelé s vyšším stupněm příspěvku na péči."}, {"question": "Co si mám vzít s sebou?", "answer": "Osobní oblečení, hygienické potřeby, oblíbené předměty z domova (fotografie, knihy). Pokoj je plně vybaven nábytkem, ložním prádlem a ručníky. Můžete si přinést i vlastní menší nábytek po dohodě."}, {"question": "Jaké jsou návštěvní hodiny?", "answer": "Návštěvy jsou vítány denně od 9:00 do 18:00. Po předchozí domluvě je možné dohodnout i návštěvu mimo tyto hodiny. Rodinní příslušníci se mohou účastnit i společných aktivit."}, {"question": "Je možné si domov předem prohlédnout?", "answer": "Ano, osobní prohlídky domova pořádáme po předchozí domluvě, zpravidla ve všední dny od 10:00 do 15:00. Kontaktujte nás telefonicky nebo e-mailem."}]');
